# BUG HUNT!

In [37]:
import sympy as sym
import numpy as np
from IPython.display import display, Math
x2 = 4


In [38]:
a,b,c,d = sym.symbols('a,b,c,d')

expr = 4*b + 5*a*a - c**3 + 5*d


In [39]:
from math import gcd
gcd(30,50)

10

In [40]:
x = sym.symbols('x')
expr = 4*x - 8
print(sym.solve(expr)[0])

2


In [133]:
import numpy as np
from IPython.display import display, Math

A = np.array([(1,2),(3,4)])
# make it look nice
display(Math(sym.latex(sym.simplify(A))))

<IPython.core.display.Math object>

In [42]:
fact_dict = sym.factorint(44)
allkeys = fact_dict.keys()
for i in allkeys:
    print('%g was present %g time%s' %(i, fact_dict[i], 's' if fact_dict[i] > 1 or fact_dict[i] == 0 else ''))


2 was present 2 times
11 was present 1 time


In [43]:
x,y = sym.symbols('x,y')

expr = 4*x - 5*y**2

expr.subs(x,5)


20 - 5*y**2

In [44]:
%%latex

$$\frac{5}{9}$$


<IPython.core.display.Latex object>

In [45]:
# print the last 3 items from a list
lst = [1,3,2,5,4,6,7,5,3,7]
lst[-3:]


[5, 3, 7]

In [46]:
from sympy.abc import x,y

expr = 2*x + 4*y

# solve for y
sym.solve(expr,y)

[-x/2]

In [47]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )

# set the element in the second row, second column to 9
A[1,1] = 9
print(A)

[[1 2]
 [3 9]]


In [48]:
import math
prices = [7, 9, 11, 8, 5, 7, 10]

m = math.inf
p = {'value':-1, 'profit': -1  }
for i in range(len(prices)):
    if prices[i] < m:
      m = prices[i]
    else:
      if prices[i] - p['value'] > p['profit'] and p['value'] > 0:
        p['profit'] = prices[i] - p['value']
      if prices[i] - m > p['profit']:
        p['value']  = m
        p['profit'] = prices[i] - m

        
print(p)


{'value': 5, 'profit': 5}


In [50]:
#np.set_printoptions(precision=0)
x,y = sym.symbols('x,y')
expr = (4 + x)*(2 - y)
erange = range(0,3)
a = np.zeros((len(erange),len(erange)),dtype=int)
for r in erange:
  for c in erange:
    a[c,r] = expr.subs({x: c, y: r})
#print(a)
display(Math(sym.latex(sym.sympify(a))))
    

<IPython.core.display.Math object>

In [65]:
x,y,w = sym.symbols('x,y,w')
f1 = x*(y + x)
f2 = 3/x + x**2
x = w * (4 - w) + w**-2*(1+w)
display(Math(sym.latex(sym.sympify(f1*f2))))
display(Math(sym.latex(sym.sympify(f2*f1))))
assert (sym.sympify(f1*f2) == sym.sympify(f2*f1))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [72]:
x = sym.symbols('x')
e1 = 2 * x + x*(4 - 6*x) + x
e2 = -x * (2/x + 4/x**2) + (4 + x)/(4 * x)
e3 = (x + 3)*(x - 3)*x*1/(9 * x)
e = [e1, e2, e3 ]
for ei in e:
  display(Math('%s \\quad \\Longleftrightarrow  \\quad %s'% (sym.latex(ei), sym.latex(sym.expand(ei)))))
  


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [89]:
from math import gcd, sin

In [76]:
a,b,c = sym.symbols('a,b,c')
display(Math('gdc(%s%s,%s%s) = %sgcd(%s,%s)' % (c,a,c,b,c,a,b)))
math.gcd(7*5, 7*6) - 7 * math.gcd(5,6)


<IPython.core.display.Math object>

0

In [86]:
r = 10
c = 15
row = [99] * c
a = [row] * r
n = np.array(a)
print(n)
for x in range(c):
  for y in range(r):
    n[y,x] = gcd(y+1,x+1)
print(n)

[[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]]
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  1  2  1  2  1  2  1  2  1  2  1  2  1]
 [ 1  1  3  1  1  3  1  1  3  1  1  3  1  1  3]
 [ 1  2  1  4  1  2  1  4  1  2  1  4  1  2  1]
 [ 1  1  1  1  5  1  1  1  1  5  1  1  1  1  5]
 [ 1  2  3  2  1  6  1  2  3  2  1  6  1  2  3]
 [ 1  1  1  1  1  1  7  1  1  1  1  1  1  7  1]
 [ 1  2  1  4  1  2  1  8  1  2  1  4  1  2  1]
 [ 1  1  3  1  1  3  1  1  9  1  1  3  1  1  3]
 [ 1  2  1  2  5  2  1  2  1 10  1  2  1  2  5]]


In [105]:
x,y = sym.symbols('x,y')

e1 = 4*x - 6
e2 = sym.sin(y)
e3 = x**2 - 9
e = [e1, e3 ]
for ei in e:
  display(Math('%s \\quad \\Longleftrightarrow  \\quad %s'% (sym.latex(ei), sym.latex(sym.solve(ei,x)))))

e = [e2 ]  
for ei in e:
  display(Math('%s \\quad \\Longleftrightarrow  \\quad %s'% (sym.latex(ei), sym.latex(sym.solve(ei,y)))))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [110]:

for i in range(2,51):
  factors = sym.factorint(i)
  if len(factors) == 1 and factors[list(factors.keys())[0]] == 1:
    print(f"{i} is a prime number")
  else:
    keys = list(factors.keys())
    print (f"{i} is a composite number with keys {keys}")

2 is a prime number
3 is a prime number
4 is a composite number with keys [2]
5 is a prime number
6 is a composite number with keys [2, 3]
7 is a prime number
8 is a composite number with keys [2]
9 is a composite number with keys [3]
10 is a composite number with keys [2, 5]
11 is a prime number
12 is a composite number with keys [2, 3]
13 is a prime number
14 is a composite number with keys [2, 7]
15 is a composite number with keys [3, 5]
16 is a composite number with keys [2]
17 is a prime number
18 is a composite number with keys [2, 3]
19 is a prime number
20 is a composite number with keys [2, 5]
21 is a composite number with keys [3, 7]
22 is a composite number with keys [2, 11]
23 is a prime number
24 is a composite number with keys [2, 3]
25 is a composite number with keys [5]
26 is a composite number with keys [2, 13]
27 is a composite number with keys [3]
28 is a composite number with keys [2, 7]
29 is a prime number
30 is a composite number with keys [2, 3, 5]
31 is a prime

In [112]:
eq = 3*x/2 + (4 - 5 * x)/3 <= 2 - (5*(2-x))/4
sym.solve(eq,x)

(22/17 <= x) & (x < oo)

In [131]:
def maxContinuousValue(l):
  prev = 0
  max = 0
  for n in l:
    prev += n
    if prev > max:
      max = prev
    elif prev < 0:
      prev = 0
    
  return max   
    

l = [34, -50, 42, 14, -5, 86]
assert (maxContinuousValue(l) == 137)
l2 =  [-5, -1, -8, -9]
assert (maxContinuousValue(l2) == 0)

     

In [126]:
def getY():
  for y in range(5,16):
    exprn = x**6 + 2 * x**4 + 6*x  - y
    exprd = x**3 + 3
    f = sym.fraction(sym.simplify(exprn/exprd))
    if f[1] == 1:
      return y
  return None

print(getY())
  

  

9


In [129]:
e1 = x**2 + 4*x + 3
e2 = 2 * y**2 - 1
e3 = 3*y**2 + 12*y
for e in [e1,e2,e3]:
  f = sym.factor(e)
  if f != e:
    display(Math('%s \\quad \\Rightarrow  \\quad %s'% (sym.latex(e), sym.latex(f))))
  else:
    display(Math('%s \\quad \\Rightarrow  \\quad \\text{%s}'% (sym.latex(e), "not factorable!")))
    

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>